### ISSUE TITLE
Parameter to view pairs on different chains

### ISSUE THREAD

**Issue by JoshMilli** [orionprotocol/sdk#15]
import { simpleFetch } from "@orionprotocol/sdk";
const pairsList = await simpleFetch(orionUnit.orionAggregator.getPairsList(BSC,FTM,ETH,ALL))();
console.log(pairsList); 

Same should be applied to WS subscriptions.

**Comment by lobotomoe** [comment]
@JoshMilli Hey. We planned to work with aggregations ins SDK in 2-4 weeks.
Currently you need initialize separated OrionUnit per network.

```ts
import { simpleFetch } from "@orionprotocol/sdk";
const ethOrionUnit = new OrionUnit('eth', 'production');
const bscOrionUnit = new OrionUnit('bsc, 'production');
const ftmOrionUnit = new OrionUnit('ftm, 'production');

const ethPairsList = await simpleFetch(ethOrionUnit.orionAggregator.getPairsList)();
const bscPairsList = await simpleFetch(bscOrionUnit.orionAggregator.getPairsList)();
const ftmPairsList = await simpleFetch(ftmOrionUnit.orionAggregator.getPairsList)();

```

**Comment by lobotomoe** [comment]
Currently available: https://github.com/orionprotocol/sdk#get-pairs
