### ISSUE TITLE
Make Swap Market parameter change

### ISSUE THREAD

**Issue by JoshMilli** [orionprotocol/sdk#9]
orionUnit.exchange
  .swapMarket({
    type: "exactSpend",
    assetIn: "ORN",
    assetOut: "USDT",
    feeAsset: "ORN",
    amount: 23.89045345,
    slippagePercent: 1,
    signer: wallet, // or signer when UI
    options: {
      route: 'pools' or 'aggregator' --------------------------------> param should be removed, swap function should calc automatically
      logger: console.log,
      // Set it to true if you want the issues associated with
      // the lack of allowance to be automatically corrected
      autoApprove: true,
    },
  })
  .then(console.log);

**Comment by lobotomoe** [comment]
Removed by https://github.com/orionprotocol/sdk/commit/fee6c06780060546c8dbb7ac3e1209d0e989c841
